# Generated by Django 4.2.11 on 2024-03-28 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTranscript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('status', models.CharField(choices=[('created', 'Request Created'), ('uploaded', 'Transcript Uploaded')], default='created', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptRequestAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transcript_of', models.CharField(max_length=264)),
                ('name', models.CharField(max_length=264)),
                ('status', models.CharField(choices=[('requested', 'Decision Pending'), ('approved', 'Request Approved'), ('declined', 'Request Declined')], default='requested', max_length=264)),
            ],
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='id',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='cid',
            field=models.CharField(max_length=264, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TranscriptRequest',
        ),
        migrations.AddField(
            model_name='transcriptrequestaccess',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcript'),
        ),
        migrations.AddField(
            model_name='transcriptrequestaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesttranscript',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcript'),
        ),
        migrations.AddField(
            model_name='requesttranscript',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
